Repository nasa/cFS, pull requests merged in 2020-05, with the labels that each got.

#80 Fix #79, Add sleep after script to avoid truncated log
  .travis.yml
Labels: CCB-20200506, IC-20200429, bug, code reviewed

#73 Fix #72, LGTM build now omits deprecated code
  .lgtm.yml
Labels: CCB-20200429, IC-20200429, code reviewed, enhancement

#85 Fix #84, Add GIT SHA
  .travis.yml
Labels: CCB Fast Track, IC-20200513, enhancement, ready for CCB

#89 Fix #88, Only inline empty functions
  .clang-format
Labels: CCB - Fast Track, IC-20200520, enhancement
