Repository nasa/cFS, pull requests merged in 2021-05, with the labels that each got.

#241 Fix #240, Add Instruction on How To Use Workflows in Contributing.md
  CONTRIBUTING.md
Labels: CCB:2021-04-14, CCB:Approved, docs

#254 Fix #251, Implement Coding Standard Rules in CodeQL
  .github/codeql/codeql-coding-standard.yml
  .github/codeql/codeql-config.yml
  .github/codeql/codeql-security.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, continuous-integration

#255 Fix #253 Add Workflow Descriptions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: CCB:Approved, docs

#258 Fix #257, Correct links to community mailing list
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: CCB:Approved, CCB:FastTrack, IC:2021-05-18, docs
