Repository nasa/cFS, pull requests merged in 2021-01, with the labels that each got.

#168 Fix #167, Update doc generation action error check
  .github/workflows/build-documentation.yml
Labels: CCB-FastTrack

#171 Fix #166 and #169, Add Static Code Analysis and Pull Request Trigger to CI workflow
  .github/workflows/build-cfs-deprecated.yml
  .github/workflows/build-cfs.yml
  .github/workflows/build-documentation.yml
  .github/workflows/static-analysis.yml
Labels: CCB-FastTrack, IC-20210105

#163 Fix #173, Create Security Policy MarkDown
  SECURITY.md
Labels: CCB-20210106, CCB:FastTrack, IC:2021-01-19, docs, security

#165 Fix #175, CodeQL Action Workflow
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-build.yml
Labels: CCB:2021-01-21, IC:2021-01-19, security
