Repository nasa/cFS, pull requests merged in 2021-08, with the labels that each got.

#323 Fix #322, Add Discussions in the Contributing Guide
  CONTRIBUTING.md
  README.md
Labels: CCB:Approved, docs

#343 Fixed minor typos in the cFS docs
  .github/workflows/README.md
  CONTRIBUTING.md
  SECURITY.md
Labels: CCB:Ready, docs, community

#339 Fix #338, Add MISRA Addons for cppcheck
  .github/workflows/static-analysis-misra.yml
Labels: CCB:Approved

#324 Fix #301, Add Github workflows to bootes.x
  .github/codeql/codeql-coding-standard.yml
  .github/codeql/codeql-security.yml
  .github/workflows/README.md
  .github/workflows/build-cfs-deprecated.yml
  .github/workflows/build-cfs.yml
  .github/workflows/build-documentation.yml
  .github/workflows/changelog.yml
  .github/workflows/codeql-build.yml
  .github/workflows/static-analysis.yml
Labels: CCB:Approved

#347 Fix #346, Use correct ref in CodeQL checkout
  .github/workflows/codeql-build.yml
Labels: CCB:Approved
