Repository nasa/cFS, pull requests merged in 2022-10, with the labels that each got.

#580 Fix #469, Addresses invalid CodeQL language option
  .github/workflows/codeql-reusable.yml
Labels: CCB:Approved

#514 Fix #416, Display cppcheck in Code Scanning Alerts Dashboard
  .github/workflows/static-analysis-misra.yml
  .github/workflows/static-analysis.yml
Labels: CCB:Approved, continuous-integration

#567 Fix #565, Remove LGTM From Documents
  README.md
  SECURITY.md
Labels: CCB:Approved

#589 Fix #583, Fetch Documentation Archives
  .github/workflows/build-deploy-doc.yml
Labels: CCB:Approved, docs

#559 Fix #554, Updated ubuntu version in CI workflows
  .github/workflows/build-cfs-deprecated.yml
  .github/workflows/build-cfs-rtems4.11.yml
  .github/workflows/build-cfs-rtems5.yml
  .github/workflows/build-cfs.yml
  .github/workflows/build-deploy-doc.yml
  .github/workflows/build-run-app.yml
  .github/workflows/codeql-reusable.yml
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  .github/workflows/unit-test-coverage.yml
Labels: CCB:Ready, CCB:FastTrack

#594 Fix #593, Add Category to Cppcheck Workflow
  .github/workflows/static-analysis.yml
Labels: CCB:Approved, continuous-integration
